CONFIG = {"link_1_length": 38,
          "link_2_length": 38,
          "robot_base_x": 20,
          "robot_base_y": 0,
          "obstacle_x": 40,
          "obstacle_y": 60,
          "obstacle_radius": 10,
          "link_discretization_param": 1,
          "angle_discretization_param": 2,
          "rubber_band": 0,
          "start_x": 20,
          "start_y": 70,
          "goal_x": 60,
          "goal_y": 40,
          "start_elbow_up": True,
          "goal_elbow_up": True,
          "attraction_gain": 1,
          "repulsion_gain": 5e3,
          "repulsion_threshold_distance": 20,
          "trajectory_proximity_threshold": 0.1}

